"""workspace_invitations added

Revision ID: 162eac0b612b
Revises: 5c021444cb78
Create Date: 2026-08-10 14:01:07.261795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '162eac0b612b'
down_revision: Union[str, Sequence[str], None] = '5c021444cb78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('inviter_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role in ('admin', 'manager', 'operator', 'viewer')", name='ck_workspace_invitations_role'),
    sa.CheckConstraint('accepted_at is null or revoked_at is null', name='ck_workspace_invitations_not_accepted_and_revoked'),
    sa.CheckConstraint('char_length(email) > 0', name='ck_workspace_invitations_email_not_empty'),
    sa.CheckConstraint('char_length(token_hash) > 0', name='ck_workspace_invitations_token_hash_not_empty'),
    sa.CheckConstraint('expires_at > created_at', name='ck_workspace_invitations_expires_after_created'),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], name='fk_workspace_invitations_inviter_user_id_users', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_workspace_invitations_workspace_id_workspaces', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_workspace_invitations_token_hash')
    )
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=254),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_table('workspace_invitations')
    # ### end Alembic commands ###
