"""copany_iin_nullable

Revision ID: 577cbdeca22f
Revises: 1b65fddf1fed
Create Date: 2026-07-26 23:09:38.991153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577cbdeca22f'
down_revision: Union[str, Sequence[str], None] = '1b65fddf1fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'iin',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'iin',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    # ### end Alembic commands ###
