"""users_roles_workspaces_added

Revision ID: 5c021444cb78
Revises: 577cbdeca22f
Create Date: 2026-08-07 18:56:31.220791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c021444cb78'
down_revision: Union[str, Sequence[str], None] = '577cbdeca22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.CheckConstraint('char_length(email) > 0', name='ck_users_email_not_empty'),
    sa.CheckConstraint('char_length(name) > 0', name='ck_users_name_not_empty'),
    sa.CheckConstraint('char_length(password_hash) > 0', name='ck_users_password_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(name) > 0', name='ck_workspaces_name_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_workspaces_name')
    )
    op.create_table('workspace_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.CheckConstraint("role in ('owner', 'admin', 'manager', 'operator', 'viewer')", name='ck_workspace_membership_role'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_workspace_memberships_user_id_users', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_workspace_memberships_workspace_id_workspaces', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workspace_id', name='uq_workspace_memberships_user_workspace')
    )
    op.add_column('companies', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_companies_iin'), 'companies', type_='unique')
    op.drop_constraint(op.f('uq_companies_name'), 'companies', type_='unique')
    op.create_unique_constraint('uq_companies_workspace_iin', 'companies', ['workspace_id', 'iin'])
    op.create_unique_constraint('uq_companies_workspace_name', 'companies', ['workspace_id', 'name'])
    op.create_foreign_key('fk_companies_workspace_id_workspaces', 'companies', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('product_suppliers', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_product_suppliers_product_supplier'), 'product_suppliers', type_='unique')
    op.create_unique_constraint('uq_product_suppliers_product_supplier_workspace', 'product_suppliers', ['product_id', 'supplier_id', 'workspace_id'])
    op.create_foreign_key('fk_product_suppliers_workspace_id_workspaces', 'product_suppliers', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_products_name_company_unit'), 'products', type_='unique')
    op.create_unique_constraint('uq_products_workspace_name_company_unit', 'products', ['workspace_id', 'name', 'company_id', 'quantity_unit'])
    op.create_foreign_key('fk_products_workspace_id_workspaces', 'products', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('restock_lines', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_restock_lines_restock_product_supplier'), 'restock_lines', type_='unique')
    op.create_unique_constraint('uq_restock_lines_workspace_restock_product_supplier', 'restock_lines', ['workspace_id', 'restock_id', 'product_supplier_id'])
    op.create_foreign_key('fk_restock_lines_workspace_id_workspaces', 'restock_lines', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('restocks', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_restocks_workspace_id_workspaces', 'restocks', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('sale_lines', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_sale_lines_sale_product_supplier'), 'sale_lines', type_='unique')
    op.create_unique_constraint('uq_sale_lines_workspace_sale_product_supplier', 'sale_lines', ['workspace_id', 'sale_id', 'product_supplier_id'])
    op.create_foreign_key('fk_sale_lines_workspace_id_workspaces', 'sale_lines', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('sales', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_sales_workspace_id_workspaces', 'sales', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('suppliers', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_suppliers_name'), 'suppliers', type_='unique')
    op.drop_constraint(op.f('uq_suppliers_phone_number'), 'suppliers', type_='unique')
    op.create_unique_constraint('uq_suppliers_workspace_name', 'suppliers', ['workspace_id', 'name'])
    op.create_unique_constraint('uq_suppliers_workspace_phone_number', 'suppliers', ['workspace_id', 'phone_number'])
    op.create_foreign_key('fk_suppliers_workspace_id_workspaces', 'suppliers', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('tags', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_tags_name'), 'tags', type_='unique')
    op.create_unique_constraint('uq_tags_workspace_name', 'tags', ['workspace_id', 'name'])
    op.create_foreign_key('fk_tags_workspace_id_workspaces', 'tags', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tags_workspace_id_workspaces', 'tags', type_='foreignkey')
    op.drop_constraint('uq_tags_workspace_name', 'tags', type_='unique')
    op.create_unique_constraint(op.f('uq_tags_name'), 'tags', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('tags', 'workspace_id')
    op.drop_constraint('fk_suppliers_workspace_id_workspaces', 'suppliers', type_='foreignkey')
    op.drop_constraint('uq_suppliers_workspace_phone_number', 'suppliers', type_='unique')
    op.drop_constraint('uq_suppliers_workspace_name', 'suppliers', type_='unique')
    op.create_unique_constraint(op.f('uq_suppliers_phone_number'), 'suppliers', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_suppliers_name'), 'suppliers', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('suppliers', 'workspace_id')
    op.drop_constraint('fk_sales_workspace_id_workspaces', 'sales', type_='foreignkey')
    op.drop_column('sales', 'workspace_id')
    op.drop_constraint('fk_sale_lines_workspace_id_workspaces', 'sale_lines', type_='foreignkey')
    op.drop_constraint('uq_sale_lines_workspace_sale_product_supplier', 'sale_lines', type_='unique')
    op.create_unique_constraint(op.f('uq_sale_lines_sale_product_supplier'), 'sale_lines', ['sale_id', 'product_supplier_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('sale_lines', 'workspace_id')
    op.drop_constraint('fk_restocks_workspace_id_workspaces', 'restocks', type_='foreignkey')
    op.drop_column('restocks', 'workspace_id')
    op.drop_constraint('fk_restock_lines_workspace_id_workspaces', 'restock_lines', type_='foreignkey')
    op.drop_constraint('uq_restock_lines_workspace_restock_product_supplier', 'restock_lines', type_='unique')
    op.create_unique_constraint(op.f('uq_restock_lines_restock_product_supplier'), 'restock_lines', ['restock_id', 'product_supplier_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('restock_lines', 'workspace_id')
    op.drop_constraint('fk_products_workspace_id_workspaces', 'products', type_='foreignkey')
    op.drop_constraint('uq_products_workspace_name_company_unit', 'products', type_='unique')
    op.create_unique_constraint(op.f('uq_products_name_company_unit'), 'products', ['name', 'company_id', 'quantity_unit'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'workspace_id')
    op.drop_constraint('fk_product_suppliers_workspace_id_workspaces', 'product_suppliers', type_='foreignkey')
    op.drop_constraint('uq_product_suppliers_product_supplier_workspace', 'product_suppliers', type_='unique')
    op.create_unique_constraint(op.f('uq_product_suppliers_product_supplier'), 'product_suppliers', ['product_id', 'supplier_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('product_suppliers', 'workspace_id')
    op.drop_constraint('fk_companies_workspace_id_workspaces', 'companies', type_='foreignkey')
    op.drop_constraint('uq_companies_workspace_name', 'companies', type_='unique')
    op.drop_constraint('uq_companies_workspace_iin', 'companies', type_='unique')
    op.create_unique_constraint(op.f('uq_companies_name'), 'companies', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_companies_iin'), 'companies', ['iin'], postgresql_nulls_not_distinct=False)
    op.drop_column('companies', 'workspace_id')
    op.drop_table('workspace_memberships')
    op.drop_table('workspaces')
    op.drop_table('users')
    # ### end Alembic commands ###
