"""create check constraints

Revision ID: 5d7c05bcf2f2
Revises: 6816febe64b4
Create Date: 2026-07-02 15:06:13.017611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d7c05bcf2f2'
down_revision: Union[str, Sequence[str], None] = '6816febe64b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('companies_iin_key'), 'companies', type_='unique')
    op.drop_constraint(op.f('companies_name_key'), 'companies', type_='unique')
    op.create_unique_constraint('uq_companies_iin', 'companies', ['iin'])
    op.create_unique_constraint('uq_companies_name', 'companies', ['name'])
    op.drop_constraint(op.f('suppliers_name_key'), 'suppliers', type_='unique')
    op.drop_constraint(op.f('suppliers_phone_number_key'), 'suppliers', type_='unique')
    op.create_unique_constraint('uq_suppliers_name', 'suppliers', ['name'])
    op.create_unique_constraint('uq_suppliers_phone_number', 'suppliers', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_suppliers_phone_number', 'suppliers', type_='unique')
    op.drop_constraint('uq_suppliers_name', 'suppliers', type_='unique')
    op.create_unique_constraint(op.f('suppliers_phone_number_key'), 'suppliers', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('suppliers_name_key'), 'suppliers', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_companies_name', 'companies', type_='unique')
    op.drop_constraint('uq_companies_iin', 'companies', type_='unique')
    op.create_unique_constraint(op.f('companies_name_key'), 'companies', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('companies_iin_key'), 'companies', ['iin'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
