"""updating relations

Revision ID: 6816febe64b4
Revises: 5b0425925f88
Create Date: 2026-06-26 19:02:51.179394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6816febe64b4'
down_revision: Union[str, Sequence[str], None] = '5b0425925f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_supplier_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_company_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_company_id_fkey'), 'products', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('products_supplier_id_fkey'), 'products', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
