"""constaint updates

Revision ID: 78bdda7dc8d7
Revises: 1f7c3a8d9b2e
Create Date: 2026-07-25 21:02:27.011641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78bdda7dc8d7'
down_revision: Union[str, Sequence[str], None] = '1f7c3a8d9b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_products_name_company', 'products', ['name', 'company_id'])
    op.drop_constraint(op.f('products_company_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'])
    op.alter_column('restock_lines', 'unit_cost_snapshot',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sale_lines', 'unit_cost_snapshot',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_lines', 'unit_cost_snapshot',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('restock_lines', 'unit_cost_snapshot',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_company_id_fkey'), 'products', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_products_name_company', 'products', type_='unique')
    op.alter_column('products', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
