"""remove stock movements

Revision ID: 8cc2700f56ec
Revises: 7a9d21c8f604
Create Date: 2026-07-18 23:30:54.680978

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8cc2700f56ec"
down_revision: Union[str, Sequence[str], None] = "7a9d21c8f604"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sales")
    op.drop_table("stock_movement_lines")
    op.drop_table("stock_movements")
    op.alter_column(
        "tags",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tags",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_table(
        "stock_movement_lines",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("movement_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("quantity_delta", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("quantity_before", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("quantity_after", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "unit_price_snapshot", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "quantity_unit_snapshot",
            sa.VARCHAR(length=20),
            server_default=sa.text("'шт'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(quantity_unit_snapshot::text) > 0",
            name=op.f("ck_stock_movement_lines_quantity_unit_snapshot_not_empty"),
        ),
        sa.CheckConstraint(
            "quantity_after >= 0", name=op.f("ck_stock_movement_lines_quantity_after")
        ),
        sa.CheckConstraint(
            "quantity_before >= 0", name=op.f("ck_stock_movement_lines_quantity_before")
        ),
        sa.CheckConstraint(
            "quantity_delta <> 0", name=op.f("ck_stock_movement_lines_quantity_delta")
        ),
        sa.CheckConstraint(
            "unit_price_snapshot IS NULL OR unit_price_snapshot > 0",
            name=op.f("ck_stock_movement_lines_unit_price_snapshot"),
        ),
        sa.ForeignKeyConstraint(
            ["movement_id"],
            ["stock_movements.id"],
            name=op.f("stock_movement_lines_movement_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("stock_movement_lines_product_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("stock_movement_lines_pkey")),
    )
    op.create_table(
        "sales",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "stock_movement_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("note", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["stock_movement_id"],
            ["stock_movements.id"],
            name=op.f("sales_stock_movement_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sales_pkey")),
        sa.UniqueConstraint(
            "stock_movement_id",
            name=op.f("uq_sales_stock_movement_id"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "movement_type", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("note", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "movement_type::text = ANY (ARRAY['in'::character varying, 'out'::character varying, 'adjustment'::character varying]::text[])",
            name=op.f("ck_stock_movements_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("stock_movements_pkey")),
    )
    # ### end Alembic commands ###
