"""audit_logs added

Revision ID: 98825bd345f5
Revises: 162eac0b612b
Create Date: 2026-08-14 22:10:19.258174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98825bd345f5'
down_revision: Union[str, Sequence[str], None] = '162eac0b612b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('actor_email', sa.String(length=254), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('entity_label', sa.String(length=255), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('target_email', sa.String(length=254), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(action) > 0', name='ck_audit_logs_action_not_empty'),
    sa.CheckConstraint('char_length(actor_email) > 0', name='ck_audit_logs_actor_email_not_empty'),
    sa.CheckConstraint('char_length(actor_name) > 0', name='ck_audit_logs_actor_name_not_empty'),
    sa.CheckConstraint('char_length(entity_label) > 0', name='ck_audit_logs_entity_label_not_empty'),
    sa.CheckConstraint('char_length(entity_type) > 0', name='ck_audit_logs_entity_type_not_empty'),
    sa.CheckConstraint('char_length(target_email) > 0', name='ck_audit_logs_target_email_not_empty'),
    sa.CheckConstraint('char_length(target_name) > 0', name='ck_audit_logs_target_name_not_empty'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name='fk_audit_logs_actor_user_id_users', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name='fk_audit_logs_target_user_id_users', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_audit_logs_workspace_id_workspaces', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_workspace_action', 'audit_logs', ['workspace_id', 'action'], unique=False)
    op.create_index('ix_audit_logs_workspace_actor', 'audit_logs', ['workspace_id', 'actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_workspace_created', 'audit_logs', ['workspace_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_workspace_entity', 'audit_logs', ['workspace_id', 'entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_workspace_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_workspace_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_workspace_actor', table_name='audit_logs')
    op.drop_index('ix_audit_logs_workspace_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
