"""add initial restock logic

Revision ID: 9fe56dafaf4d
Revises: 8cc2700f56ec
Create Date: 2026-07-18 23:54:58.945217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe56dafaf4d'
down_revision: Union[str, Sequence[str], None] = '8cc2700f56ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restock_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restock_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('delta_units', sa.Integer(), nullable=False),
    sa.CheckConstraint('delta_units > 0', name='ck_restock_lines_delta_units'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restock_id'], ['restocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restock_lines')
    op.drop_table('restocks')
    # ### end Alembic commands ###
