"""upgrade restock logic

Revision ID: d267434cc44d
Revises: 9fe56dafaf4d
Create Date: 2026-07-19 15:45:21.525800

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d267434cc44d"
down_revision: Union[str, Sequence[str], None] = "9fe56dafaf4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "restock_lines", sa.Column("restock_quantity", sa.Integer(), nullable=False)
    )
    op.add_column(
        "restock_lines", sa.Column("unit_cost_snapshot", sa.Integer(), nullable=True)
    )
    op.add_column(
        "restock_lines",
        sa.Column("quantity_unit_snapshot", sa.String(length=20), nullable=False),
    )
    op.create_unique_constraint(
        "uq_restock_lines_restock_product",
        "restock_lines",
        ["restock_id", "product_id"],
    )
    op.drop_constraint(
        op.f("restock_lines_product_id_fkey"), "restock_lines", type_="foreignkey"
    )
    op.create_foreign_key(None, "restock_lines", "products", ["product_id"], ["id"])
    op.drop_column("restock_lines", "delta_units")
    op.add_column(
        "restocks",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.create_check_constraint(
        "ck_restock_lines_restock_quantity",
        "restock_lines",
        "restock_quantity > 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("restocks", "created_at")
    op.add_column(
        "restock_lines",
        sa.Column("delta_units", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "restock_lines", type_="foreignkey")
    op.create_foreign_key(
        op.f("restock_lines_product_id_fkey"),
        "restock_lines",
        "products",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "uq_restock_lines_restock_product", "restock_lines", type_="unique"
    )
    op.drop_column("restock_lines", "quantity_unit_snapshot")
    op.drop_column("restock_lines", "unit_cost_snapshot")
    op.drop_column("restock_lines", "restock_quantity")
    op.create_check_constraint(
        "ck_restock_lines_delta_units",
        "restock_lines",
        "delta_units > 0",
    )
    # ### end Alembic commands ###
