"""add sale logic

Revision ID: ebffd8b37282
Revises: d267434cc44d
Create Date: 2026-07-20 14:20:28.962382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebffd8b37282'
down_revision: Union[str, Sequence[str], None] = 'd267434cc44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sale_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_snapshot', sa.Integer(), nullable=True),
    sa.Column('unit_sale_price_snapshot', sa.Integer(), nullable=True),
    sa.Column('quantity_unit_snapshot', sa.String(length=20), nullable=False),
    sa.CheckConstraint('sale_quantity > 0', name='ck_sale_lines_sale_quantity'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_id', 'product_id', name='uq_sale_lines_sale_product')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_lines')
    op.drop_table('sales')
    # ### end Alembic commands ###
