export const elements = {
  appMessage: getElement("#app-message"),
  navTabs: Array.from(document.querySelectorAll("[data-view-tab]")),
  navMenuToggles: Array.from(document.querySelectorAll("[data-view-menu-views]")),
  views: {
    dashboard: getElement("#dashboard"),
    products: getElement("#products"),
    companies: getElement("#companies"),
    suppliers: getElement("#suppliers"),
    restocks: getElement("#restocks"),
    sales: getElement("#sales"),
  },
  dashboard: {
    form: getElement("#dashboard-sales-period-form"),
    daysInput: getElement("#dashboard-sales-period-input"),
    bestSalesModeSelect: getElement("#dashboard-best-sales-mode-select"),
    salesValue: getElement("#dashboard-sales-value-card"),
    salesCount: getElement("#dashboard-sales-count-card"),
    lowStock: getElement("#dashboard-low-stock"),
    outOfStock: getElement("#dashboard-out-of-stock"),
    refreshButton: getElement("#dashboard-sales-period-button"),
    trendSummary: getElement("#dashboard-sales-trend-summary"),
    salesChart: getElement("#dashboard-sales-chart"),
    salesTrendEmpty: getElement("#dashboard-sales-trend-empty"),
    bestSalesSummary: getElement("#dashboard-best-sales-summary"),
    bestSalesMetricHeading: getElement("#dashboard-best-sales-metric-heading"),
    bestSalesEmpty: getElement("#dashboard-best-sales-empty"),
    topSuppliersEmpty: getElement("#dashboard-top-suppliers-empty"),
    salesDailyTableBody: getElement("#dashboard-sales-daily-table-body"),
    bestSalesTableBody: getElement("#dashboard-best-sales-table-body"),
    topSuppliersTableBody: getElement("#dashboard-top-suppliers-table-body"),
  },
  products: {
    searchForm: getElement("#products-search-form"),
    searchInput: getElement("#products-search-input"),
    searchButton: getElement("#products-search-button"),
    count: getElement("#products-count"),
    loading: getElement("#products-loading"),
    error: getElement("#products-error"),
    empty: getElement("#products-empty"),
    table: getElement("#products-table"),
    tableBody: getElement("#products-table-body"),
    pagination: getElement("#products-pagination"),
    previousPageButton: getElement("#products-previous-page-button"),
    nextPageButton: getElement("#products-next-page-button"),
    pageSummary: getElement("#products-page-summary"),
    modal: getElement("#product-create-modal"),
    form: getElement("#product-create-form"),
    submitButton: getElement("#product-create-submit-button"),
    createError: getElement("#product-create-error"),
    companyModeInputs: Array.from(document.querySelectorAll("[name='product_company_mode']")),
    companyExistingPanel: getElement("#product-create-company-existing-panel"),
    companyNewPanel: getElement("#product-create-company-new-panel"),
    companySearchInput: getElement("#product-create-company-search"),
    companyIdInput: getElement("#product-create-company-id"),
    companyResults: getElement("#product-create-company-results"),
    companySelected: getElement("#product-create-company-selected"),
    companySelectedName: getElement("#product-create-company-selected-name"),
    companySelectedMeta: getElement("#product-create-company-selected-meta"),
    companyClearButton: getElement("#product-create-company-clear-button"),
    companyLookupMessage: getElement("#product-create-company-lookup-message"),
    linkEnabledInput: getElement("#product-create-link-enabled"),
    supplierSection: getElement("#product-create-supplier-section"),
    supplierModeInputs: Array.from(document.querySelectorAll("[name='product_supplier_mode']")),
    supplierExistingPanel: getElement("#product-create-supplier-existing-panel"),
    supplierNewPanel: getElement("#product-create-supplier-new-panel"),
    supplierSearchInput: getElement("#product-create-supplier-search"),
    supplierIdInput: getElement("#product-create-supplier-id"),
    supplierResults: getElement("#product-create-supplier-results"),
    supplierSelected: getElement("#product-create-supplier-selected"),
    supplierSelectedName: getElement("#product-create-supplier-selected-name"),
    supplierSelectedMeta: getElement("#product-create-supplier-selected-meta"),
    supplierClearButton: getElement("#product-create-supplier-clear-button"),
    supplierLookupMessage: getElement("#product-create-supplier-lookup-message"),
    detailModal: getElement("#product-detail-modal"),
    detailTitle: getElement("#product-detail-modal-title"),
    detailEditButton: getElement("#product-detail-edit-button"),
    detailLoading: getElement("#product-detail-loading"),
    detailError: getElement("#product-detail-error"),
    detailContent: getElement("#product-detail-content"),
    detailEditError: getElement("#product-detail-edit-error"),
    detailView: getElement("#product-detail-view"),
    detailEditForm: getElement("#product-detail-edit-form"),
    detailEditNameInput: getElement("#product-detail-edit-name"),
    detailEditUnitInput: getElement("#product-detail-edit-unit"),
    detailEditThresholdInput: getElement("#product-detail-edit-threshold"),
    detailId: getElement("#product-detail-id"),
    detailCreatedAt: getElement("#product-detail-created-at"),
    detailCompany: getElement("#product-detail-company"),
    detailUnit: getElement("#product-detail-unit"),
    detailThreshold: getElement("#product-detail-threshold"),
    detailTotalQuantity: getElement("#product-detail-total-quantity"),
    detailTags: getElement("#product-detail-tags"),
    detailSupplierCount: getElement("#product-detail-supplier-count"),
    detailSuppliersEmpty: getElement("#product-detail-suppliers-empty"),
    detailSuppliersTable: getElement("#product-detail-suppliers-table"),
    detailSuppliersBody: getElement("#product-detail-suppliers-body"),
    detailCancelEditButton: getElement("#product-detail-cancel-edit-button"),
    detailSaveButton: getElement("#product-detail-save-button"),
    detailCloseButton: getElement("#product-detail-close-button"),
  },
  companies: getListElements("companies", "company"),
  suppliers: getListElements("suppliers", "supplier"),
  restocks: {
    ...getOperationElements("restocks", "restock"),
    detailModal: getElement("#restock-detail-modal"),
    detailTitle: getElement("#restock-detail-modal-title"),
    detailLoading: getElement("#restock-detail-loading"),
    detailError: getElement("#restock-detail-error"),
    detailContent: getElement("#restock-detail-content"),
    detailId: getElement("#restock-detail-id"),
    detailCreatedAt: getElement("#restock-detail-created-at"),
    detailLinesCount: getElement("#restock-detail-lines-count"),
    detailCosts: getElement("#restock-detail-costs"),
    detailNote: getElement("#restock-detail-note"),
    detailLinesEmpty: getElement("#restock-detail-lines-empty"),
    detailLinesTable: getElement("#restock-detail-lines-table"),
    detailLinesBody: getElement("#restock-detail-lines-body"),
  },
  sales: {
    ...getOperationElements("sales", "sale"),
    detailModal: getElement("#sale-detail-modal"),
    detailTitle: getElement("#sale-detail-modal-title"),
    detailLoading: getElement("#sale-detail-loading"),
    detailError: getElement("#sale-detail-error"),
    detailContent: getElement("#sale-detail-content"),
    detailId: getElement("#sale-detail-id"),
    detailCreatedAt: getElement("#sale-detail-created-at"),
    detailLinesCount: getElement("#sale-detail-lines-count"),
    detailRevenue: getElement("#sale-detail-revenue"),
    detailCosts: getElement("#sale-detail-costs"),
    detailProfit: getElement("#sale-detail-profit"),
    detailNote: getElement("#sale-detail-note"),
    detailLinesEmpty: getElement("#sale-detail-lines-empty"),
    detailLinesTable: getElement("#sale-detail-lines-table"),
    detailLinesBody: getElement("#sale-detail-lines-body"),
  },
};

function getListElements(key, singular) {
  return {
    searchForm: getElement(`#${key}-search-form`),
    searchInput: getElement(`#${key}-search-input`),
    searchButton: getElement(`#${key}-search-button`),
    count: getElement(`#${key}-count`),
    loading: getElement(`#${key}-loading`),
    error: getElement(`#${key}-error`),
    empty: getElement(`#${key}-empty`),
    table: getElement(`#${key}-table`),
    tableBody: getElement(`#${key}-table-body`),
    pagination: getElement(`#${key}-pagination`),
    previousPageButton: getElement(`#${key}-previous-page-button`),
    nextPageButton: getElement(`#${key}-next-page-button`),
    pageSummary: getElement(`#${key}-page-summary`),
    modal: getElement(`#${singular}-create-modal`),
    form: getElement(`#${singular}-create-form`),
    submitButton: getElement(`#${singular}-create-submit-button`),
    createError: getElement(`#${singular}-create-error`),
  };
}

function getOperationElements(key, singular) {
  return {
    filterForm: getElement(`#${key}-filter-form`),
    dateFromInput: getElement(`#${key}-date-from-input`),
    dateToInput: getElement(`#${key}-date-to-input`),
    resetButton: getElement(`#${key}-reset-button`),
    count: getElement(`#${key}-count`),
    loading: getElement(`#${key}-loading`),
    error: getElement(`#${key}-error`),
    empty: getElement(`#${key}-empty`),
    table: getElement(`#${key}-table`),
    tableBody: getElement(`#${key}-table-body`),
    pagination: getElement(`#${key}-pagination`),
    previousPageButton: getElement(`#${key}-previous-page-button`),
    nextPageButton: getElement(`#${key}-next-page-button`),
    pageSummary: getElement(`#${key}-page-summary`),
    modal: getElement(`#${singular}-create-modal`),
    form: getElement(`#${singular}-create-form`),
    submitButton: getElement(`#${singular}-create-submit-button`),
    createError: getElement(`#${singular}-create-error`),
    addLineButton: getElement(`#${singular}-create-add-line-button`),
    linesContainer: getElement(`#${singular}-create-lines`),
  };
}

function getElement(selector) {
  const element = document.querySelector(selector);

  if (!element) {
    throw new Error(`Missing frontend element: ${selector}`);
  }

  return element;
}
