const state = {
  apiBase: localStorage.getItem(API_BASE_STORAGE_KEY) || DEFAULT_API_BASE,
  companies: [],
  suppliers: [],
  products: [],
  stockMovements: [],
  dashboardMovements: [],
  productSummary: createEmptyProductSummary(),
  salesDateFrom: getTodayDateInputValue(),
  salesDateTo: getTodayDateInputValue(),
  salesSummary: createEmptySalesSummary(),
  pagination: {
    companies: createPageState(DEFAULT_LOOKUP_PAGE_SIZE),
    suppliers: createPageState(DEFAULT_LOOKUP_PAGE_SIZE),
    products: createPageState(DEFAULT_PRODUCT_PAGE_SIZE),
    stockMovements: createPageState(DEFAULT_MOVEMENT_PAGE_SIZE),
  },
  activeTab: "dashboard",
  activeDrawerForm: null,
  stockMovementsLoaded: false,
  movementProductCache: new Map(),
  productFormTags: [],
  selectedTagFilters: [],
  editingProductId: null,
  searchTerm: "",
  stockFilter: "all",
  productSort: DEFAULT_PRODUCT_SORT,
  productSortOrder: DEFAULT_PRODUCT_SORT_ORDER,
};

let movementLineCounter = 0;
let saleLineCounter = 0;
let movementProductSearchCounter = 0;
const movementProductSearchTimers = new Map();
let tagSearchCounter = 0;
const tagSearchTimers = new Map();

const refs = {
  tabButtons: [...document.querySelectorAll("[data-tab-target]")],
  tabPanels: [...document.querySelectorAll("[data-tab-panel]")],
  apiSettings: document.querySelector("#api-settings"),
  apiBase: document.querySelector("#api-base"),
  notice: document.querySelector("#notice"),
  drawer: document.querySelector("#form-drawer"),
  drawerBackdrop: document.querySelector("#drawer-backdrop"),
  drawerClose: document.querySelector("#drawer-close"),
  drawerTitle: document.querySelector("#drawer-title"),
  drawerEyebrow: document.querySelector("#drawer-eyebrow"),
  drawerForms: [...document.querySelectorAll("[data-drawer-form]")],
  addProductButton: document.querySelector("#add-product-button"),
  addSupplierButton: document.querySelector("#add-supplier-button"),
  addCompanyButton: document.querySelector("#add-company-button"),
  addMovementButton: document.querySelector("#add-movement-button"),
  dashboardAddProductButton: document.querySelector("#dashboard-add-product-button"),
  dashboardAddSaleButton: document.querySelector("#dashboard-add-sale-button"),
  dashboardAddMovementButton: document.querySelector("#dashboard-add-movement-button"),
  dashboardRefreshButton: document.querySelector("#dashboard-refresh-button"),
  dashboardLowStockButton: document.querySelector("#dashboard-low-stock-button"),
  dashboardOutOfStockButton: document.querySelector("#dashboard-out-of-stock-button"),
  dashboardViewMovementsButton: document.querySelector(
    "#dashboard-view-movements-button",
  ),
  dashboardTotalProducts: document.querySelector("#dashboard-total-products"),
  dashboardLowStock: document.querySelector("#dashboard-low-stock"),
  dashboardOutOfStock: document.querySelector("#dashboard-out-of-stock"),
  dashboardSalesForm: document.querySelector("#dashboard-sales-form"),
  dashboardSalesDateFrom: document.querySelector("#dashboard-sales-date-from"),
  dashboardSalesDateTo: document.querySelector("#dashboard-sales-date-to"),
  dashboardSalesRevenue: document.querySelector("#dashboard-sales-revenue"),
  dashboardSalesUnits: document.querySelector("#dashboard-sales-units"),
  dashboardSalesOperations: document.querySelector("#dashboard-sales-operations"),
  dashboardSalesChart: document.querySelector("#dashboard-sales-chart"),
  dashboardBestSellers: document.querySelector("#dashboard-best-sellers"),
  dashboardMovementList: document.querySelector("#dashboard-movement-list"),
  refreshButton: document.querySelector("#refresh-button"),
  productSearch: document.querySelector("#product-search"),
  productSearchTagSuggestions: document.querySelector(
    "#product-search-tag-suggestions",
  ),
  selectedSearchTags: document.querySelector("#selected-search-tags"),
  stockFilter: document.querySelector("#stock-filter"),
  productSort: document.querySelector("#product-sort"),
  productSortOrder: document.querySelector("#product-sort-order"),
  productTableBody: document.querySelector("#products-table-body"),
  productPagination: document.querySelector("#product-pagination"),
  productPageInfo: document.querySelector("#product-page-info"),
  productForm: document.querySelector("#product-form"),
  productId: document.querySelector("#product-id"),
  productName: document.querySelector("#product-name"),
  productPurchasePrice: document.querySelector("#product-purchase-price"),
  productMarginPercent: document.querySelector("#product-margin-percent"),
  productFloorPrice: document.querySelector("#product-floor-price"),
  productSalePrice: document.querySelector("#product-sale-price"),
  productQuantity: document.querySelector("#product-quantity"),
  productQuantityUnit: document.querySelector("#product-quantity-unit"),
  productLowStockThreshold: document.querySelector(
    "#product-low-stock-threshold",
  ),
  productCompany: document.querySelector("#product-company"),
  productSupplier: document.querySelector("#product-supplier"),
  productTagList: document.querySelector("#product-tag-list"),
  productTagInput: document.querySelector("#product-tag-input"),
  addProductTagButton: document.querySelector("#add-product-tag-button"),
  productTagSuggestions: document.querySelector("#product-tag-suggestions"),
  productSubmit: document.querySelector("#product-submit"),
  cancelEdit: document.querySelector("#cancel-edit"),
  companyForm: document.querySelector("#company-form"),
  companyName: document.querySelector("#company-name"),
  companyIin: document.querySelector("#company-iin"),
  companySubmit: document.querySelector("#company-submit"),
  companyTableBody: document.querySelector("#company-table-body"),
  companyPagination: document.querySelector("#company-pagination"),
  companyPageInfo: document.querySelector("#company-page-info"),
  supplierForm: document.querySelector("#supplier-form"),
  supplierName: document.querySelector("#supplier-name"),
  supplierPhone: document.querySelector("#supplier-phone"),
  supplierSubmit: document.querySelector("#supplier-submit"),
  supplierTableBody: document.querySelector("#supplier-table-body"),
  supplierPagination: document.querySelector("#supplier-pagination"),
  supplierPageInfo: document.querySelector("#supplier-page-info"),
  movementRefreshButton: document.querySelector("#movement-refresh-button"),
  movementTableBody: document.querySelector("#movement-table-body"),
  movementPagination: document.querySelector("#movement-pagination"),
  movementPageInfo: document.querySelector("#movement-page-info"),
  movementForm: document.querySelector("#movement-form"),
  movementType: document.querySelector("#movement-type"),
  addMovementLineButton: document.querySelector("#add-movement-line-button"),
  movementLines: document.querySelector("#movement-form-lines"),
  movementNote: document.querySelector("#movement-note"),
  movementSubmit: document.querySelector("#movement-submit"),
  saleForm: document.querySelector("#sale-form"),
  addSaleLineButton: document.querySelector("#add-sale-line-button"),
  saleLines: document.querySelector("#sale-form-lines"),
  saleTotal: document.querySelector("#sale-form-total"),
  saleNote: document.querySelector("#sale-note"),
  saleSubmit: document.querySelector("#sale-submit"),
};
